# Generated by Django 5.2.5 on 2025-08-24 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('lastUpdated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='events.events')),
            ],
        ),
    ]
