# Generated by Django 5.2.5 on 2025-08-24 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdates',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date', to='events.events'),
        ),
    ]
