# Generated by Django 5.2.5 on 2025-08-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_participants', models.IntegerField()),
                ('n_officials', models.IntegerField()),
                ('n_all', models.IntegerField()),
                ('n_users', models.IntegerField()),
                ('n_queries', models.IntegerField()),
                ('n_displays', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
