# Generated by Django 5.2.5 on 2025-08-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
