# Generated by Django 5.2.5 on 2025-08-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_info_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
