# Generated by Django 5.2.5 on 2025-08-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
