# Generated by Django 5.2.5 on 2025-08-24 18:32

from django.db import migrations
import uuid

def copy_slug_from_details(apps, schema_editor):
    Clubs = apps.get_model('club', 'Clubs')
    for club in Clubs.objects.all():
        # detailsフィールドが辞書型で、かつ'slug'キーを持っているか確認
        if isinstance(club.details, dict) and 'slug' in club.details:
            slug_value = club.details.get('slug')
            if slug_value:
                club.slug = slug_value
            else:
                # もしdetails内のslugが空だった場合のフォールバック処理
                club.slug = f"club-{uuid.uuid4().hex[:8]}"
        else:
            # detailsにslugがなかった場合のフォールバック処理
            club.slug = f"club-{uuid.uuid4().hex[:8]}"
        
        club.save()
# 逆方向は何もしない、という空の関数を用意
def reverse_copy_slug(apps, schema_editor):
    pass # 何もしない

class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_clubs_slug'),
    ]

    operations = [
        migrations.RunPython(copy_slug_from_details, reverse_copy_slug),
    ]
