# Generated by Django 5.2.5 on 2025-08-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20250825_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
